server:
  port: 9092
  tomcat:
    max-http-form-post-size: 100MB
  
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/goldplan
        username: goldplan
        password: goldplan
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update         
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB

#h2 properties
#spring:
#    datasource:
#        url: jdbc:h2:mem:testdb
#        driverClassName: org.h2.Driver
#        username: sa
#        password: password
#    jpa:
#        database-platform: org.hibernate.dialect.H2Dialect
#        show-sql: true